#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.18ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.Flatpak.SystemHelper.conf 1.1.1-1\~ flatpak -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.18ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'flatpak-system-helper.service' >/dev/null || true
fi
# End automatically added section
