#!/bin/bash


if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root" >&2
  exit 1
fi

cd "$(dirname "$0")"

script/install-tools
script/build-rootfs
script/config-rootfs
script/init-chroot
script/exit-chroot
exit 0
script/clean-chroot
script/build-image

echo "Done."