#!/bin/bash

# mount filesystems
sudo mount -o bind /run/ oracular-rootfs/run
sudo cp /etc/hosts oracular-rootfs/etc
sudo mount --bind /dev/ oracular-rootfs/dev
sudo mount --bind /dev/pts oracular-rootfs/dev/pts
sudo mount --bind /proc oracular-rootfs/proc
sudo mount --bind /sys oracular-rootfs/sys
# enter chroot
sudo chroot oracular-rootfs /bin/bash
# umount filesystems
sudo umount oracular-rootfs/run
sudo umount oracular-rootfs/sys
sudo umount oracular-rootfs/dev/pts
sudo umount oracular-rootfs/dev
sudo umount oracular-rootfs/proc
# exit chroot